name: affiliate_platform
description: Affiliate Platform
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  connectivity_plus: ^5.0.2
  delightful_toast: ^1.1.0
  elegant_notification: ^1.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.2
  sidebarx: ^0.16.3
  webview_flutter: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
